services:

  flask:
    build:
      dockerfile: ./server_web.dockerfile

    ports:
      - "5000"

    deploy:
      replicas: 3

    networks:
      - internal

  balancer-nginx:
    image: nginx:1.25.4

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "0.0.0.0:80:80"

    networks:
      - internal
      - external

networks:

  internal:
    name: internal

  external:
    name: external
